"use strict";
let storeLocation = ['Switzerland', 'Greece', 'Turkey', 'India', 'Singapore', 'Bali', 'UK', 'Finland', 'USA', 'Italy'];
console.log(storeLocation);
let alphabatecArray = storeLocation.slice().sort();
console.log(alphabatecArray);
console.log(storeLocation);
let reversArray = storeLocation.slice().reverse();
console.log(reversArray);
console.log(storeLocation);
storeLocation.reverse();
console.log(storeLocation);
storeLocation.reverse();
console.log(storeLocation);
storeLocation.sort();
console.log(storeLocation);
storeLocation.sort().reverse();
console.log(storeLocation);
